import "server-only";
import { getTextModels, getImageModel } from "@/lib/gemini";
import { POLLINATIONS_LABEL } from "@/lib/pollinations";

/** Teks kredit untuk artikel ai-generated, diambil dari model yang sedang dipakai. */
export function aiCredit(): string {
  const text = getTextModels()[0] ?? "Gemini";
  const images =
    process.env.GEMINI_IMAGE_ENABLED === "false"
      ? `Pollinations (${POLLINATIONS_LABEL})`
      : `Gemini (${getImageModel()})`;
  return `Generated by Gemini (${text}) and ${images}`;
}
